### PR TITLE
Fix stub generator and add new snippets

### LINKED ISSUE #278: Fix stub generators
Currently, only a set number of stubs (either 10 or 11) can be generated using the stub generator. After that, we believe some platform caching gets triggered and so the same stub will be recorded for all the following snippets.

We can avoid this by cache busting the `test-tempfile.js` file.

### PR DESCRIPTION
**Pull request by linclark**
Fixes #278 

@bgrins, mind giving this a quick review? It's what we worked on yesterday

### CODE REVIEW

File: devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/head.js [hunk 1]
```diff
@@ -22,6 +22,20 @@ const { prepareMessage } = require("devtools/client/webconsole/new-console-outpu
 const BASE_PATH = "../../../../devtools/client/webconsole/new-console-output/test/fixtures";
 const TEMP_FILE_PATH = OS.Path.join(`${BASE_PATH}/stub-generators`, "test-tempfile.js");
 
+/**
+ * Close a tab and if necessary, the toolbox that belongs to it
+ * @param {Tab} tab The tab to close.
+ * @return {Promise} Resolves when the toolbox and tab have been destroyed and
+ * closed.
+ */
+var closeTabAndToolbox = Task.async(function* (tab = gBrowser.selectedTab) {
```
Comment (bgrins) [inline devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/head.js]: This is already defined in shared-head.js so should be able to remove it here.  See: https://dxr.mozilla.org/mozilla-central/source/devtools/client/framework/test/shared-head.js#350

File: devtools/client/webconsole/new-console-output/test/fixtures/stubs/consoleApi.js [hunk 2]
```diff
@@ -7,7 +7,7 @@
  * THIS FILE IS AUTOGENERATED. DO NOT MODIFY BY HAND. RUN TESTS IN FIXTURES/ TO UPDATE.
  */
 
-const { ConsoleMessage } = require("devtools/client/webconsole/new-console-output/types");
+const { ConsoleMessage, NetworkEventMessage } = require("devtools/client/webconsole/new-console-output/types");
```
Comment (bgrins) [inline devtools/client/webconsole/new-console-output/test/fixtures/stubs/consoleApi.js:10]: The NetworkEventMessage import doesn't seem to be used in these files - is this intentional?

File: devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/stub-snippets.js [hunk 3]
```diff
@@ -3,6 +3,10 @@
 
 "use strict";
 
+var {DebuggerServer} = require("devtools/server/main");
```
Comment (bgrins) [inline devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/stub-snippets.js:6]: These imports don't seem to be used

**Review by bgrins — APPROVED** [review]
Looks good to me, see the comments

File: devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/stub-snippets.js (hunk 3 above)
Comment (linclark) [reply devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/stub-snippets.js:6]: Ah yeah, I pulled this out of another PR I was working on. I'm going to leave it in for now because we'll definitely be using it in a PR in the next few days.

File: devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/head.js (hunk 1 above)
Comment (linclark) [reply devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/head.js]: Removed

File: devtools/client/webconsole/new-console-output/test/fixtures/stubs/consoleApi.js (hunk 2 above)
Comment (linclark) [reply devtools/client/webconsole/new-console-output/test/fixtures/stubs/consoleApi.js:10]: It's added automatically by the stub generator. We only output one header for the different files. We will eventually want to revamp all of the stub generation code anyway, so I'm going to leave that as is for now.
