### PR TITLE
Incorporate markup changes from network request stack trace changes (Bug 1281732) #107

### LINKED ISSUE #107: Incorporate markup changes from network request stack trace changes (Bug 1281732)
Some changes are landing in m-c to make the structure of all message types more consistent.  See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1281732#c57:

```
message-body-wrapper
- message-flex-body
  - message-body
  - message-repeats
  - message-location
- attachment (stacktrace or consoletable)
```

I believe it also gets rid of some extra elements in the hierarchy.  We should confirm once that bug lands that our makup matches the normal frontend.

This should wait until #105 lands

### PR DESCRIPTION
**Pull request by jsnajdr**
Fixes #107. Use the same markup structure (`message`, `message-body-wrapper`, `message-flex-body`, `message-body`) for all types of messages.

I also added location to `PageError` messages (until now, they were only in `ConsoleAPICall`) in order to better test the new structure.

A good next step would be to factor the markup structure into a common component, as it is now duplicated across several places. The only variable part is the class list for the `message` element and the markup of the `message-body`. Everything else is common code.

### CODE REVIEW

File: devtools/client/webconsole/new-console-output/components/message-types/console-api-call.js [hunk 1]
```diff
@@ -45,6 +45,15 @@ function ConsoleApiCall(props) {
 
   const icon = MessageIcon({level});
   const repeat = MessageRepeat({repeat: message.repeat});
+  const shouldRenderFrame = frame && frame.source !== "debugger eval code";
+  const location = dom.span({ className: "message-location devtools-monospace" },
```
Comment (linclark) [inline devtools/client/webconsole/new-console-output/components/message-types/console-api-call.js:49]: Is anything in the HTML structure changing here? Or is this just a differing code organization?

File: devtools/client/webconsole/new-console-output/components/message-types/default-renderer.js [hunk 2]
```diff
@@ -8,14 +8,27 @@
...
 
+const MessageIcon = createFactory(require("devtools/client/webconsole/new-console-output/components/message-icon").MessageIcon);
+
 DefaultRenderer.displayName = "DefaultRenderer";
 
 function DefaultRenderer(props) {
-  return dom.div({},
-    "This message type is not supported yet."
+  const { message } = props;
+  const { source, type, level } = message;
```
Comment (linclark) [inline devtools/client/webconsole/new-console-output/components/message-types/default-renderer.js]: I appreciate the thought here, but given #217 there's a decent chance that things will be coming in to this component without one of [source, type, level]. If you want to provide the coder with more useful than what the message current does, please serialize the message coming in and show that.

**Comment by linclark** [comment]
Overall, this is looking good. We should future-proof the DefaultRenderer before committing.

> A good next step would be to factor the markup structure into a common component, as it is now duplicated across several places. The only variable part is the class list for the message element and the markup of the message-body. Everything else is common code.

Agreed. The plan is to do this once we have all the message types implemented. That way we don't end up with premature generalization of anything. I'll make an issue to track that work. I'm guessing it will be ready in a couple of sprints.

File: devtools/client/webconsole/new-console-output/components/message-types/default-renderer.js (hunk 2 above)
Comment (jsnajdr) [inline devtools/client/webconsole/new-console-output/components/message-types/default-renderer.js]: You mean the whole `message` object? With all potentially large info like `stacktrace` or table data? I'd guess that providing a short message about the `source` and `type` is better, even when sometimes it will be `undefined` - it gives you actionable info about what message types you're not implementing.

File: devtools/client/webconsole/new-console-output/components/message-types/console-api-call.js (hunk 1 above)
Comment (jsnajdr) [inline devtools/client/webconsole/new-console-output/components/message-types/console-api-call.js:49]: I removed one extra `span` element and moved the `attachment` to the right location. Several subelements (like `icon`, `repeat` and `location`) are factored out so that the return value is one giant nested blob.

File: devtools/client/webconsole/new-console-output/components/message-types/default-renderer.js (hunk 2 above)
Comment (linclark) [inline devtools/client/webconsole/new-console-output/components/message-types/default-renderer.js]: If something doesn't have a level, you'll be passing `undefined` into `MessageIcon`. Then this will call `l10n.getStr` with it, which will [throw an exception](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/utils.js#382) because it can't find the corresponding level string.

Comment (jsnajdr) [reply devtools/client/webconsole/new-console-output/components/message-types/default-renderer.js]: Alright, I'll keep the `DefaultRenderer` unchanged in this patch.

**Comment by linclark** [comment]
Great, thank you. Committed and pushed.
