### PR TITLE
Bug 1306751 - New console frontend: Emit new-message from componentDi…

### LINKED ISSUE #338: Emit new-message from componentDidMount
This will help ensure tests that depend on `waitForMessages` work.

This depends on #327, which turns Message into a class based component with a ref.
1. Pass the event emitter down to the Message component
2. In the Message component, emit the event from `componentDidMount` if `this.messageNode` is not null

### PR DESCRIPTION
**Pull request by linclark**
Fixes #338 
## Testing instructions
1. Run browser_webconsole_init.js

@bgrins lmk if you see a better way than threading the function through all of the components

### CODE REVIEW

**Comment by linclark** [comment]
Also, we don't currently store the packet. We could add it to the MESSAGE_ADD action if you think it's worthwhile.

File: devtools/client/webconsole/new-console-output/components/message.js [hunk 1]
```diff
@@ -47,8 +47,12 @@ const Message = createClass({
   },
 
   componentDidMount() {
-    if (this.props.scrollToMessage && this.messageNode) {
-      this.messageNode.scrollIntoView();
+    debugger
```
Comment (nchevobbe) [inline devtools/client/webconsole/new-console-output/components/message.js]: oops :)

Comment (linclark) [reply devtools/client/webconsole/new-console-output/components/message.js]: whoops! fixed, thanks

**Comment by bgrins** [comment]
> Also, we don't currently store the packet. We could add it to the MESSAGE_ADD action if you think it's worthwhile.

As far as I can tell, none of the tests that we need to support use packet.  I'd say don't even include that in the emitted object at all (or pass in an empty object from componentWillMount) and let's see if try is OK with it.  At least then we will get a 'packet is undefined' error if it is needed

File: devtools/client/webconsole/new-console-output/new-console-output-wrapper.js [hunk 2]
```diff
@@ -16,12 +16,13 @@ const FilterBar = React.createFactory(require("devtools/client/webconsole/new-co
 
 const store = configureStore();
 
-function NewConsoleOutputWrapper(parentNode, jsterm, toolbox, owner) {
+function NewConsoleOutputWrapper(parentNode, jsterm, toolbox, owner, emitNewMessage) {
   this.parentNode = parentNode;
   this.parentNode = parentNode;
```
Comment (bgrins) [inline devtools/client/webconsole/new-console-output/new-console-output-wrapper.js]: Just saw this - looks like this line is duplicated

File: devtools/client/webconsole/new-console-output/new-console-output-wrapper.js [hunk 3]
```diff
@@ -46,6 +47,7 @@ NewConsoleOutputWrapper.prototype = {
       openLink: (url) => {
         this.owner.openLink(url);
       },
+      emitNewMessage: this.emitNewMessage,
```
Comment (bgrins) [inline devtools/client/webconsole/new-console-output/new-console-output-wrapper.js]: Personally, I'd move the definition of emitNewMessage here instead of passing it into the constructor from webconsole.js, since this is where we are kind of defining all sorts of other tool integration pieces, and I like seeing them all in one place.  The thing it would be emitted on in this case would be: `this.jsterm.hud`.

But, it's not a big deal and up to you either way

**Comment by bgrins** [comment]
> @bgrins lmk if you see a better way than threading the function through all of the components

I wish we didn't have to do so much plumbing to get a prop down to the message, but I guess this is the most correct way to do it.  I'm tempted to be cheap on this 'test only' code path and just reach into the global to emit from the message (which would save a lot of code), but since you already have this working in a more standard way I'm happy with it.

File: devtools/client/webconsole/new-console-output/components/message.js [hunk 4]
```diff
@@ -47,8 +47,11 @@ const Message = createClass({
   },
 
   componentDidMount() {
-    if (this.props.scrollToMessage && this.messageNode) {
-      this.messageNode.scrollIntoView();
+    if (this.messageNode && this.props.emitNewMessage) {
+      this.props.emitNewMessage({}, this.messageNode);
```
Comment (bgrins) [inline devtools/client/webconsole/new-console-output/components/message.js]: As I mentioned in the comment - let's try removing the packet arg altogether and see how tests like it

File: devtools/client/webconsole/webconsole.js [hunk 5]
```diff
@@ -3266,10 +3273,6 @@ WebConsoleConnectionProxy.prototype = {
    */
   dispatchMessageAdd: function(packet) {
     this.webConsoleFrame.newConsoleOutput.dispatchMessageAdd(packet);
-    this.webConsoleFrame.emit("new-messages", new Set([{
-      response: packet,
-      node: this.webConsoleFrame.newConsoleOutput.getLastMessage(),
```
Comment (bgrins) [inline devtools/client/webconsole/webconsole.js:3271]: Can getLastMessage be removed now?

**Review by bgrins — APPROVED** [review]
Thanks!  See inline comments

File: devtools/client/webconsole/new-console-output/new-console-output-wrapper.js (hunk 2 above)
Comment (linclark) [reply devtools/client/webconsole/new-console-output/new-console-output-wrapper.js]: removed

File: devtools/client/webconsole/new-console-output/new-console-output-wrapper.js (hunk 3 above)
Comment (linclark) [reply devtools/client/webconsole/new-console-output/new-console-output-wrapper.js]: good idea, moved.

File: devtools/client/webconsole/new-console-output/components/message.js (hunk 4 above)
Comment (linclark) [reply devtools/client/webconsole/new-console-output/components/message.js]: 👍

File: devtools/client/webconsole/webconsole.js (hunk 5 above)
Comment (linclark) [reply devtools/client/webconsole/webconsole.js:3271]: Ah, right right. I think it can be
